FROM python:3.12-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "bwa_frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]